name: CI/CD Pipeline for Next.js
on:
  push:
    branches:
      - deploy-lara
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use your preferred OS
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./frontend
      - name: Run Lint
        run: npm run lint
        working-directory: ./frontend
      - name: Build Next.js app
        run: npm run build
        working-directory: ./frontend
      - name: Deploy to Vercel
        working-directory: ./frontend
        env:
          VERCEL_TOKEN: ${{ secrets.LARA_VERCEL_TOKEN }}
        run: |
          npx vercel deploy --prod --token $VERCEL_TOKEN --confirm